### ISSUE TITLE
FEATURE: Babel Macro for babel-plugin-better-async-await

### ISSUE THREAD

**Issue by cyrus-za** [vivek12345/babel-plugin-better-async-await#1]
I'd like to be able to use this with [CRA](https://github.com/facebook/create-react-app) so if we can get this into a [Macro](https://github.com/kentcdodds/babel-plugin-macros) that would be amazing. 

I am rather busy this week but might have some time in a week or two to take a look at creating this if someone hasnt picked it up yet.

**Comment by vivek12345** [comment]
Hi @cyrus-za thank you for the suggestion 👍 
I have made a babel-macro for the same.
https://www.npmjs.com/package/better-async-await.macro

Please let me know if you face any issues around it and would be happy to hear more from you.

Also I will be more than happy reviewing and merging any new feature requests that you might consider useful for this project as a PR.

**Comment by cyrus-za** [comment]
Thanks. Only saw your reply now. I'll chwck it out and close the issue
